// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctlmjjfnbneqbxjiomjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0bG1qamZuYm5lcWJ4amlvbWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDg2OTYsImV4cCI6MjA3MDU4NDY5Nn0.OAUYw0B1K6nlUKx2ZJ1au29L6Ll_Sk6uR1JpWssBlio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});